blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import RecordListView, RecordDetailView, RecordCreateView, RecordUpdateView, RecordDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
    path('toggle/<slug:slug>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_app.urls', namespace='mailing_app')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_app.apps import MailingAppConfig
from mailing_app.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MailingAttemptListView, set_mailing_status, HomePageView

app_name = MailingAppConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing_attempt_list/', MailingAttemptListView.as_view(), name='mailing_attempt_list'),
    path('set_mailing_status/<int:pk>', login_required(set_mailing_status), name='set_mailing_status')
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, CustomLoginView, CustomPasswordResetView, \
    CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, verify_account, \
    UserListView, set_user_status

app_name = UsersConfig.name


urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('verify/<int:user_pk>/', verify_account, name='verify_account'),
    path('users_list/', login_required(UserListView.as_view()), name='users_list'),
    path('users_status/<int:pk>/', set_user_status, name='users_status'),
]

mailing_app/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(max_length=50, verbose_name='контактный email', unique=True)
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    comments = models.TextField(verbose_name='комментарий', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.email} ({self.full_name})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело сообщения')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.subject


class Mailing(models.Model):
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    FREQUENCY_CHOICES = [
        (DAILY, 'Ежедневно'),
        (WEEKLY, 'Еженедельно'),
        (MONTHLY, 'Ежемесячно')
    ]
    CREATED = 'created'
    STARTED = 'started'
    FINISHED = 'finished'
    STATUS_CHOICES = [
        (CREATED, 'Создана'),
        (STARTED, 'Запущена'),
        (FINISHED, 'Завершена')
    ]
    mailing_time = models.TimeField(verbose_name='Время рассылки')
    frequency = models.CharField(max_length=50, verbose_name='Периодичность', choices=FREQUENCY_CHOICES, default=DAILY)
    mailing_status = models.CharField(max_length=50, verbose_name='Статус рассылки', choices=STATUS_CHOICES,
                                      default=CREATED)

    clients = models.ManyToManyField(Client, verbose_name='Клиенты для рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='тема письма')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'ID: {self.id} - время рассылки: {self.mailing_time}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                'set_mailing_status',
                'Can set mailing status'
            ),
        ]


class MailingAttempt(models.Model):
    SENT = 'sent'
    FAILED = 'failed'
    PENDING = 'pending'

    STATUS_CHOICES = [
        (SENT, 'Отправлено'),
        (FAILED, 'Не удалось отправить'),
        (PENDING, 'В ожидании')
    ]
    time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=50, verbose_name='статус попытки', choices=STATUS_CHOICES, default=PENDING)
    server_response = models.CharField(**NULLABLE, max_length=150, verbose_name='ответ почтового сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

mailing_app/forms.py
from django import forms
from mailing_app.models import Mailing


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ('user',)

mailing_app/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, DetailView, ListView, DeleteView, TemplateView

from blog.models import Blog
from mailing_app.forms import MailingForm
from mailing_app.models import Mailing, Client, Message, MailingAttempt
from mailing_app.services import cache_message


class HomePageView(TemplateView):
    template_name = 'mailing_app/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_mailing_all'] = Mailing.objects.all().count()
        context_data['count_mailing_active'] = Mailing.objects.filter(mailing_status=Mailing.CREATED).count()
        context_data['count_unique_clients'] = Client.objects.distinct().count()
        context_data['blog'] = Blog.objects.all().order_by('?')[:3]
        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing_app.set_mailing_status'):
            return queryset

        return queryset.filter(user=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('email', 'full_name', 'comments')
    success_url = reverse_lazy('mailing_app:client_list')

    def form_valid(self, form):
        client = form.save()
        client.user = self.request.user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    fields = ('email', 'full_name', 'comments')
    success_url = reverse_lazy('mailing_app:client_list')

    def test_func(self):
        client = self.get_object()
        user = self.request.user
        return user.is_authenticated and (client.user == user or user.has_perm('mailing_app.change_client'))


class ClientDeleteView(UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing_app:client_list')

    def test_func(self):
        client = self.get_object()
        user = self.request.user
        return user.is_authenticated and (client.user == user or user.has_perm('mailing_app.delete_client'))


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing_app.view_mailing'):
            return queryset

        return queryset.filter(user=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.has_perm('mailing_app.view_mailing') or self.request.user == self.object.user:
            return self.object
        raise HttpResponseForbidden


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing_app:mailing_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
        return super().form_valid(form)


class MailingUpdateView(UserPassesTestMixin, UpdateView):
    model = Mailing
    fields = '__all__'
    success_url = reverse_lazy('mailing_app:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        return user.is_authenticated and (mailing.user == user or user.has_perm('mailing_app.change_mailing'))


class MailingDeleteView(UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing_app:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        return user.is_authenticated and (mailing.user == user or user.has_perm('mailing_app.delete_mailing'))


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        queryset = cache_message(Message, 'message')
        if self.request.user.has_perm('mailing_app.set_mailing_status'):
            return queryset
        return queryset.filter(user=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('mailing_app:message_list')

    def form_valid(self, form):
        message = form.save()
        message.user = self.request.user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UserPassesTestMixin, UpdateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('mailing_app:message_list')

    def test_func(self):
        message = self.get_object()
        user = self.request.user
        return user.is_authenticated and (message.user == user or user.has_perm('mailing_app.change_message'))


class MessageDeleteView(UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing_app:message_list')

    def test_func(self):
        message = self.get_object()
        user = self.request.user
        return user.is_authenticated and (message.user == user or user.has_perm('mailing_app.delete_message'))


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = 'mailing_app/mailing_attempt_list.html'


@permission_required(perm='mailing_app.set_mailing_status')
def set_mailing_status(request, pk):
    obj = get_object_or_404(Mailing, pk=pk)
    if obj:
        obj.mailing_status = Mailing.CREATED
        obj.save()
    return redirect(request.META.get('HTTP_REFERER'))

mailing_app/templates/mailing_app/includes/inc_main_menu.html
<div class="container-fluid text-center py-3">
    <a class="btn" style="font-size: 25px; color: black; text-shadow: #1b1b1b;" href="{% url 'mailing_app:home' %}">Сервис управления рассылками</a>
</div>
<div class="col d-flex justify-content-start">
    {% if user.is_authenticated %}
         <a class="p-2 btn btn-outline-dark" href="{% url 'users:profile' %}">Профиль</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'users:logout' %}">Выйти</a>
    {% else %}
        <a class="p-2 btn btn-outline-dark" href="{% url 'users:register' %}">Регистрация</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'users:login' %}">Войти</a>
    {% endif %}
    <a class="p-2 btn btn-outline-dark" href="{% url 'mailing_app:client_list' %}">Клиенты</a>
    {% if perms.users.set_is_active %}
        <a class="p-2 btn btn-outline-dark" href="{% url 'users:users_list' %}">Пользователи</a>
    {% endif %}
</div>

<div class="col d-flex justify-content-center align-items-center">
    <div class="dropdown">
        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Меню
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% if perms.users.set_is_active %}
            <a class="dropdown-item" href="{% url 'users:users_list' %}">Пользователи</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'blog:record_list' %}">Блог</a>
            <a class="dropdown-item" href="{% url 'mailing_app:client_list' %}">Клиенты</a>
            <a class="dropdown-item" href="{% url 'mailing_app:message_list' %}">Сообщения</a>
            <a class="dropdown-item" href="{% url 'mailing_app:mailing_list' %}">Рассылки</a>
            <a class="dropdown-item" href="{% url 'mailing_app:mailing_attempt_list' %}">Статус рассылок</a>
        </div>

    </div>
</div>

<div class="col d-flex justify-content-end align-items-center">
    <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
            <circle cx="10.5" cy="10.5" r="7.5"></circle>
            <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
        </svg>
    </a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'blog:record_list' %}">Блог</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'mailing_app:message_list' %}">Сообщения</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'mailing_app:mailing_list' %}">Все рассылки</a>
    <a class="p-2 btn btn-outline-dark" href="{% url 'mailing_app:mailing_attempt_list' %}">Статус рассылок</a>
</div>

<style>
    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-toggle {
        border: 1px solid #ccc;
        border-radius: 20px;
        display: inline-block;
        padding: 10px 20px;
        cursor: pointer;
        background-color: #fff;
        transition: all 0.3s ease-in-out;
    }

    .dropdown-toggle:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
    }

    .dropdown-toggle:active {
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }

    .dropdown-menu {
        position: absolute;
        top: 100%;
        left: 0;
        z-index: 1000;
        display: none;
        float: left;
        min-width: 10rem;
        padding: .10rem 10px;
        margin: .125rem 0 0;
        font-size: 1rem;
        color: #212529;
        text-align: left;
        list-style: none;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid rgba(0, 0, 0, .15);
        border-radius: 15px 15px;
        transform: translateY(-1px);
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
    }

    .dropdown:hover .dropdown-menu {
        display: block;
        animation: dropdown-fade-in 0.3s ease-in-out forwards;
    }

</style>