blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import RecordListView, RecordDetailView, RecordCreateView, RecordUpdateView, RecordDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
    path('toggle/<slug:slug>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_app.urls', namespace='mailing_app')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from transliterate import translit
from mailing_app.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='Slug')
    body = models.TextField(verbose_name='Содержимое статьи')
    picture = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    views = models.IntegerField(verbose_name='Количество просмотров', default=0, **NULLABLE)
    published_on = models.BooleanField(default=False, verbose_name='дата публикации')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        permissions = [
            (
                'set_published_blog',
                'Can publish blog'
            )
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            transliterated_title = translit(self.title, 'ru', reversed=True)
            self.slug = slugify(transliterated_title, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:record_detail', kwargs={'slug': self.slug})

    def toggle_published(self):
        self.published_on = not self.published_on
        self.save()

blog/forms.py
from blog.models import Blog
from mailing_app.forms import StyleFormMixin
from django import forms


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'
        exclude = ('slug', 'views', )

blog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import cache_blog


class RecordListView(ListView):
    model = Blog
    queryset = Blog.objects.filter(published_on=True)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blog'] = cache_blog()
        return context_data


class RecordCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:record_list')


class RecordUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:record_list')

    def get_success_url(self):
        return self.object.get_absolute_url()


class RecordDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.views += 1
        obj.save()
        return obj


class RecordDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:record_list')


@permission_required('blog.set_published_blog')
def toggle_activity(request, slug):
    record_item = get_object_or_404(Blog, slug=slug)
    record_item.toggle_published()
    return redirect(reverse('blog:record_detail', args=[record_item.slug]))

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <h2 class="mt-4 mb-4 text-center">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" class="mt-3">
                            {% csrf_token %}
                            <p>
                                Вы уверены, что хотите удалить "{{ object.title }}"?
                            </p>
                            <div class="row justify-content-center">
                                <a href="{% url 'blog:record_list' %}" class="btn btn-secondary mr-3">Вернуться к
                                    записям</a>
                                <button class="btn btn-danger" type="submit">Удалить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    {% load tags %}
    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                {{ object.title }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ object.body }}</h5>
                <img src="{% mediapath object.picture %}" class="card-img-top mx-auto d-block img-fluid" alt=""
                     style="width: auto; height: auto;">
                <p class="card-text">Просмотры: {{ object.views }}</p>
                {% if perms.blog.change_blog %}
                    <a href="{% url 'blog:update_record' object.slug %}" class="btn btn-warning">Изменить
                        запись</a>
                {% endif %}
                {% if perms.blog.delete_blog %}
                    <a href="{% url 'blog:delete_record' object.slug %}" class="btn btn-danger">Удалить
                        запись</a>
                {% endif %}
                <br><br>
                <a href="{% url 'blog:record_list' %}" class="btn btn-secondary">Все записи</a>
                {% if perms.blog.set_published_blog %}
                    {% if object.published_on == True %}
                        <a href="{% url 'blog:toggle_activity' object.slug %}" class="btn btn-outline-danger">Снять с
                            публикации</a>
                    {% else %}
                        <a href="{% url 'blog:toggle_activity' object.slug %}" class="btn btn-outline-primary">Опубликовать</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="card-footer text-muted">
                <p class="card-text">
                    Создана: {{ object.created_date }}<br>
                    Опубликована: {{ object.published_on }}
                </p>
            </div>
        </div>
    </div>

    <style>
        .card {
            margin-top: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
        }

        .card-header {
            font-size: 24px;
            background-color: #eee;
            font-weight: bold;
        }

        .card-body {
            text-align: center;
        }

        .card-text {
            font-size: 18px;
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group text-center">
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>

        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .card-body form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
            padding: 0 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }

        .form-group input[type="time"],
        .form-group input[type="text"],
        .form-group input[type="text"],
        .form-group input[type="text"],
        .form-group input[type="email"] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #f1f1f1;
            margin-bottom: 0.5rem;
            width: 100%;
            box-sizing: border-box;
        }

        .form-group input[type="time"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="email"]:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    {% load tags %}
    <div class="container-center">
        <h1 class="text-center">Блог</h1>
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col" style="text-align: center">ID</th>
                <th scope="col" style="text-align: center">Заголовок</th>
                <th scope="col" style="text-align: center">Содержание</th>
                <th scope="col" style="text-align: center">Превью</th>
                <th scope="col" style="text-align: center">Просмотры</th>
                 <th scope="col" style="text-align: center"></th>
            </tr>
            </thead>
            <tbody class="table-group-divider table-divider-primary">
            {% for object in object_list %}
                {% if object.published_on %}
                    <tr>
                        <th scope="row">{{ object.pk }}</th>
                        <td class="text-center">{{ object.title }}</td>
                        <td class="text-center">{{ object.body|truncatechars:100 }}</td>
                        <td class="text-center">
                            <img src="{% mediapath object.picture %}" class="rounded mx-auto d-block" alt=""
                                 height="100">
                        </td>
                        <td style="text-align: center">{{ object.views }}</td>
                        <td>
                            <a href="{% url 'blog:record_detail' object.slug %}" class="btn btn-info btn-sm">Перейти
                                к записи</a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <div class="container" style="text-align: center">
            {% if user.is_superuser or perms.blog.add_blog %}
            <a href="{% url 'blog:create_record' %}" class="btn btn-outline-secondary btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">
                Создать запись
            </a>
             {% endif %}
        </div>
    </div>
    <style>
        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}