blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import RecordListView, RecordDetailView, RecordCreateView, RecordUpdateView, RecordDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
    path('toggle/<slug:slug>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_app.urls', namespace='mailing_app')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_app.apps import MailingAppConfig
from mailing_app.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MailingAttemptListView, set_mailing_status, HomePageView

app_name = MailingAppConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing_attempt_list/', MailingAttemptListView.as_view(), name='mailing_attempt_list'),
    path('set_mailing_status/<int:pk>', login_required(set_mailing_status), name='set_mailing_status')
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, CustomLoginView, CustomPasswordResetView, \
    CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView, verify_account, \
    UserListView, set_user_status

app_name = UsersConfig.name


urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('verify/<int:user_pk>/', verify_account, name='verify_account'),
    path('users_list/', login_required(UserListView.as_view()), name='users_list'),
    path('users_status/<int:pk>/', set_user_status, name='users_status'),
]

users/models.py
from django.contrib.auth.hashers import make_password
from django.db import models


from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager

NULLABLE = {'blank': True, 'null': True}


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='статус активации')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            (
                'set_is_active',
                'Can block user'
            ),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UsernameField, AuthenticationForm, \
    PasswordResetForm, SetPasswordForm
from django.utils.translation import gettext_lazy as _
from mailing_app.forms import StyleFormMixin
from users.models import User


class CustomUserChangeForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'avatar')
        field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class CustomUserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
        field_classes = {'username': UsernameField}


class CustomAuthenticationForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User

    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User


class CustomResetConfirmForm(SetPasswordForm):
    class Meta:
        model = User

users/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView, ListView

from users.forms import CustomUserChangeForm, CustomUserRegisterForm, CustomAuthenticationForm, CustomPasswordResetForm, \
    CustomResetConfirmForm
from users.models import User


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.set_is_active'


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('mailing_app:mailing_list')

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = CustomUserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        subject = 'Верификация учетной записи'
        message = f'Здравствуйте, пожалуйста проверьте свою учетную запись, перейдя по этой ссылке: ' \
                  f'http://localhost:8000{reverse_lazy("users:verify_account", kwargs={"user_pk": user.pk})}.'
        from_email = settings.EMAIL_HOST_USER
        recipient_list = [user.email]
        send_mail(subject, message, from_email, recipient_list, fail_silently=False)
        return response


def verify_account(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    user.is_active = True
    user.save()
    login(request, user)
    return redirect(to=reverse('users:login'))


class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('users:login')


class CustomPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/email_reset.html'
    from_email = settings.EMAIL_HOST_USER


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomResetConfirmForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


@permission_required(perm='users.set_is_active')
def set_user_status(request, pk):
    obj = get_object_or_404(User, pk=pk)
    if obj.is_superuser:
        return HttpResponseForbidden()
    if obj.is_active:
        obj.is_active = False
    else:
        obj.is_active = True
    obj.save()

    return redirect(request.META.get('HTTP_REFERER'))

users/templates/users/email_reset.html
Cброс пароля для электронной почты {{ email }}.
Перейдите по ссылке ниже:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

users/templates/users/login.html
{% extends 'mailing_app/base.html' %}


{% block content %}
        <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-12">
                <div class="card shadow-sm my-4">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пользователь</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <a class="text-muted" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                            <a class="text-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
                            <div class="form-group text-center">
                                <a href="{% url 'mailing_app:mailing_list' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Войти</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>

        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .card-body form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
            padding: 0 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }

        .form-group input[type="email"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }

        .form-group input[type="email"],
        .form-group input[type="text"],
        .form-group input[type="text"] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #f1f1f1;
            margin-bottom: 0.5rem;
            width: 100%;
            box-sizing: border-box;
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div style="display: flex; flex-direction: column; align-items: center; margin: 0 auto;"><h2 class="active">Создан
        новый пароль</h2>
        <a href="{% url 'users:login' %}" class="btn btn-link">
            Войти заново
        </a>
    </div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пароль</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h1 class="h3 mb-3 fw-normal">Введите новый пароль</h1>
                            <div class="form-group text-center">
                                {{ form.as_p }}
                                <button class="p-2 btn btn-outline-success" type="submit">Сохранить</button>
                                <div class="form-group text-center">
                                    <a class="btn btn-link" href="{% url 'users:login' %}">Вернуться</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div style="display: flex; flex-direction: column; align-items: center; margin: 0 auto;"><h2 class="active">Ссылка
        выслана на
        почту</h2> <a href="{% url 'mailing_app:mailing_list' %}" class="btn btn-link"> Вернуться к рассылкам </a>
    </div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пароль</h4>
                    </div>
                    <div class="card-body text-center">
                        <form method="post" action="{% url 'users:password_reset' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                                <button class="p-2 btn btn-dark" type="submit">Сбросить пароль</button>
                            </div>
                            <div class="form-group text-center">
                                <a class="btn btn-outline-dark" href="{% url 'users:login' %}">Вернуться</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing_app/base.html' %}


{% block content %}
        <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-12">
                <div class="card shadow-sm my-4">
                    <div class="card-header text-center">
                        <h4 class="card-title">Пользователь</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="form-group text-center">
                                <a href="{% url 'mailing_app:mailing_list' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>

        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 2px 4px rgba(0, 0, 0, 0.3);
            width: 100%;

        }

        .card-body form {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .form-group {
            margin-bottom: 1rem;
            text-align: left;
            padding: 0 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: bold;
        }

        .form-group input[type="email"]:focus,
        .form-group input[type="text"]:focus,
        .form-group input[type="text"]:focus {
            outline: none;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
        }

        .form-group input[type="email"],
        .form-group input[type="text"],
        .form-group input[type="text"] {
            padding: 0.5rem;
            border: none;
            border-radius: 5px;
            background-color: #f1f1f1;
            margin-bottom: 0.5rem;
            width: 100%;
            box-sizing: border-box;
        }

        .btn {
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing_app/base.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Пользователи</h1>
        <table class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">email</th>
                    <th scope="col" style="text-align: center">Блокировка</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                    {% if not item.is_superuser %}
                        <tr>
                            <th class="text-center">{{ item.pk }}</th>
                            <td class="text-center">{{ item.email }}</td>
                            <td class="text-center">
                                {% if perms.users.set_is_active %}
                                    {% if item.is_active %}
                                        <a href="{% url 'users:users_status' item.pk %}" class="btn btn-outline-danger">Заблокировать</a>
                                    {% else %}
                                        <a href="{% url 'users:users_status' item.pk %}"
                                           class="btn btn-outline-primary">Снять блокировку</a>
                                    {% endif %}
                                {% endif %}
                            </td>

                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </table>
    </div>
    <style>
        .btn {
            margin-top: 5px;
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            transform: translateY(-3px);
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
        }

        .btn:active {
            transform: translateY(-1px);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% endblock %}